Repository blinqas/station, pull requests merged in 2023-10, with the labels that each got.

#66 Improved Bootstrap Process, Documentation, and Repo Automation #32
  bootstrap/.gitignore
  bootstrap/README.md
  bootstrap/bootstrap.sh
  bootstrap/github_repository.tf
  bootstrap/providers.tf
  bootstrap/providers/providers.tf
  bootstrap/providers/providers_local_state.tf
  bootstrap/tfe_variables.tf
  bootstrap/tfe_workspace.tf
  bootstrap/variables.tf
Labels: enhancement

#70 Fix #69
  test/user_assigned_identities_test.tf
  user_assigned_identities.tf
  user_assigned_identity/group_member.tf
  user_assigned_identity/variables.tf
  variables.tf
Labels: bug

#72 (breaking) Change var.group_membership type to be a map. Fixes #71
  group_membership.tf
  variables.tf
Labels: bug

#79 Fix #77 and #78
  resource_group.tf
  tfe.tf
  variables.tf
Labels: bug, enhancement

#76 Bug/Fixed booststrap script for mac users
  bootstrap/bootstrap.sh
Labels: bug
