Repository blinqas/station, pull requests merged in 2023-09, with the labels that each got.

#15 Terraform Cloud integration
  DESIGN_DESICIONS.md
  README.md
  hashicorp/tfe/outputs.tf
  hashicorp/tfe/terraform.tf
  hashicorp/tfe/tfe_project.tf
  hashicorp/tfe/tfe_variable.tf
  hashicorp/tfe/tfe_workspace.tf
  hashicorp/tfe/variables.tf
  outputs.tf
  terraform.tf
  tests/tfe/bootstrap/.gitignore
  tests/tfe/bootstrap/README.md
  tests/tfe/bootstrap/application.tf
  tests/tfe/bootstrap/federated_identity_credential.tf
  tests/tfe/bootstrap/outputs.tf
  tests/tfe/bootstrap/role_assignment.tf
  tests/tfe/bootstrap/service_principal.tf
  tests/tfe/bootstrap/state_storage.tf
  tests/tfe/bootstrap/terraform.tf
  tests/tfe/bootstrap/variables.tf
  tests/tfe/terraform_cloud.tf
  tests/tfe/tfe_projects.tf
  tfe.tf
  variables.tf
Labels: enhancement

#24 Populate TFC workspace with variables required for Azure auth + some extras
  tfe.tf
Labels: enhancement

#31 Improved bootstrap process
  bootstrap/.gitignore
  bootstrap/README.md
  bootstrap/application.tf
  bootstrap/bootstrap.sh
  bootstrap/federated_identity_credential.tf
  bootstrap/outputs.tf
  bootstrap/providers.tf
  bootstrap/providers/providers.tf
  bootstrap/providers/providers_local_state.tf
  bootstrap/role_assignment.tf
  bootstrap/service_principal.tf
  bootstrap/terraform.tf
  bootstrap/tfe_organization.tf
  bootstrap/tfe_project.tf
  bootstrap/tfe_variables.tf
  bootstrap/tfe_workspace.tf
  bootstrap/variables.tf
  example/.gitignore
  example/terraform.tf
  tests/basic.tf
  tests/bootstrap/.gitignore
  tests/bootstrap/README.md
  tests/bootstrap/application.tf
  tests/bootstrap/backend.conf
  tests/bootstrap/federated_identity_credential.tf
  tests/bootstrap/outputs.tf
  tests/bootstrap/resource_group.tf
  tests/bootstrap/role_assignment.tf
  tests/bootstrap/state_storage.tf
  tests/bootstrap/terraform.tf
  tests/bootstrap/variables.tf
  tests/terraform.tf
  tests/tfe/bootstrap/.gitignore
  tests/tfe/bootstrap/README.md
  tests/tfe/bootstrap/outputs.tf
  tests/tfe/bootstrap/service_principal.tf
  tests/tfe/bootstrap/variables.tf
  tests/tfe/terraform_cloud.tf
  tests/tfe/tfe_projects.tf
Labels: enhancement

#35 Terraform Cloud defaults
  application_federated_identity_credential.tf
  hashicorp/tfe/outputs.tf
Labels: enhancement

#36 Terraform Cloud improvements
  application_federated_identity_credential.tf
  hashicorp/tfe/outputs.tf
  hashicorp/tfe/variables.tf
  tfe.tf
  variables.tf
Labels: bug, enhancement

#41 Fix azuread_group_member members being an empty tuple
  group/group.tf
Labels: enhancement

#48 Added type constraint to input variable `applications`
  DESIGN_DESICIONS.md
  application/azuread_application.tf
  application/variables.tf
  applications.tf
  test/.gitignore
  test/README.md
  test/application_tests.tf
  test/azuread_application_published_app_ids.tf
  test/azuread_client_config.tf
  test/msgraph_service_principal.tf
  test/providers.tf
  test/tfc.tf
  test/variables.tf
  variables.tf
Labels: enhancement

#51 Added type constraints to `resource_groups`
  resource_group.tf
  variables.tf
Labels: documentation, enhancement

#52 Added type constraints to `federated_identity_credential_config`
  application_federated_identity_credential.tf
  variables.tf
Labels: enhancement

#54 Use managed identity instead of application with service principal
  app_role_assignment.tf
  application.tf
  application_federated_identity_credential.tf
  applications.tf
  group_membership.tf
  groups.tf
  outputs.tf
  role_assignment.tf
  service_principal.tf
  tfe.tf
  user_assigned_identities.tf
  user_assigned_identity/outputs.tf
  variables.tf
Labels: enhancement

#56 Add resource_group_name as an input variable
  resource_group.tf
  variables.tf
Labels: enhancement, breaking-change

#60 Fix #59
  user_assigned_identities.tf
  user_assigned_identity/variables.tf
  variables.tf
Labels: bug

#62 Fix #61
  tfe.tf
Labels: bug
