Repository blinqas/station, pull requests merged in 2025-05, with the labels that each got.

#198 chore: removed old references to module_output_to_workspace_var and improve application output with id and display name
  README.md
  tests/tfe.tftest.hcl
  tfe.tf
  variables.tf
Labels: chore

#203 refactor!: environment name
  README.md
  resource_group.tf
  tags.tf
  tests/identity.tftest.hcl
  tfe.tf
  user_assigned_identities.tf
  variables.tf
Labels: refactor, breaking_changes

#160 chore: update `azuread` provider to v3
  application/providers.tf
  bootstrap/providers/providers_local_state.tf
  group/providers.tf
  groups.tf
  providers.tf
  user_assigned_identity/group_member.tf
  user_assigned_identity/providers.tf
Labels: chore

#209 fix: vnet creation without peerings and subnet delegations
  README.md
  connectivity.tf
  variables.tf
Labels: bug
