Repository blinqas/station, pull requests merged in 2025-02, with the labels that each got.

#179 refactor(tfe)!: changed the tfe block to expect a project name and id instead of name
  README.md
  application_federated_identity_credential.tf
  hashicorp/tfe/outputs.tf
  hashicorp/tfe/tfe_project.tf
  hashicorp/tfe/tfe_workspace.tf
  hashicorp/tfe/variables.tf
  test/test_applications.tf
  test/test_groups.tf
  test/test_user_assigned_identities.tf
  test/test_workload_identity.tf
  tests/group.tftest.hcl
  tests/setup-tfe-project/main.tf
  tests/tfe.tftest.hcl
  tfe.tf
  variables.tf
Labels: breaking-change, refactor

#182 feat: migrate all tests over to the terraform test framework and the use_existing param for the var.application.service_principal
  .github/workflows/terraform.yaml
  .gitignore
  README.md
  application/azuread_application.tf
  application/outputs.tf
  group/outputs.tf
  providers.tf
  test/.gitignore
  test/README.md
  test/assets/logo.png
  test/azuread_application_published_app_ids.tf
  test/azuread_client_config.tf
  test/azurerm_client_config.tf
  test/msgraph_service_principal.tf
  test/providers.tf
  test/test_applications.tf
  test/test_groups.tf
  test/test_user_assigned_identities.tf
  test/test_workload_identity.tf
  test/tfc.tf
  test/variables.tf
  tests/application.tftest.hcl
  tests/group.tftest.hcl
  tests/setup-application/main.tf
  tests/setup-groups/main.tf
  tests/setup-uai/main.tf
  tests/tfe.tftest.hcl
  tests/user_assigned_identities.tftest.hcl
  user_assigned_identity/outputs.tf
  variables.tf
Labels: feature

#132 feat!: add an identity block to configure the landing zone identity
  README.md
  application_federated_identity_credential.tf
  docs/DESIGN_DESICIONS/identity_block.md
  group_membership.tf
  outputs.tf
  role_assignment.tf
  tests/application.tftest.hcl
  tests/group.tftest.hcl
  tests/identity.tftest.hcl
  tests/setup-tfe-project/main.tf
  tests/setup-tfe-project/variables.tf
  tests/user_assigned_identities.tftest.hcl
  user_assigned_identities.tf
  user_assigned_identity/directory_role_assignment.tf
  user_assigned_identity/outputs.tf
  user_assigned_identity/role_assignments.tf
  user_assigned_identity/variables.tf
  variables.identity.tf
  variables.tf
Labels: feature, breaking_changes

#189 fix: removed provider config block
  providers.tf
Labels: bug

#190 fix(application): Ignore changes on app_roles
  application/azuread_application.tf
Labels: bug
